language: bash
sudo: required
cache: apt

# we don't use docker but this triggers travis-ci to provide Ubuntu 14.04
services:
  - docker

before_install:
  - lsb_release -a
  - sudo apt-get update -qq

install:
  - sudo apt-get install --yes libhttp-tiny-perl librdf-query-perl
  - cpanm --installdeps --skip-satisfied --local-lib local .

script:
  - prove -Ilocal/lib/perl5 -v

env: RELEASE_TESTING=1 AUTOMATED_TESTING=1
